// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_source_moments
List cpp_source_moments(SEXP X_source, const bool center, const int block_size, const int n_threads, const bool compute_covariance);
RcppExport SEXP _LDRegularization_cpp_source_moments(SEXP X_sourceSEXP, SEXP centerSEXP, SEXP block_sizeSEXP, SEXP n_threadsSEXP, SEXP compute_covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_source(X_sourceSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_covariance(compute_covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_source_moments(X_source, center, block_size, n_threads, compute_covariance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LDRegularization_cpp_source_moments", (DL_FUNC) &_LDRegularization_cpp_source_moments, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_LDRegularization(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
