// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_projected_bootstrap_rank
List cpp_projected_bootstrap_rank(const arma::mat& X_target, const bool center, const int n_boot, const double anchor_fraction, const double guard_fraction, const double target_fraction, const double basis_fraction, const int initial_rank, const int rank_block, const int oversample, const int bootstrap_extra, const int power_iterations, const int n_threads, const double seed);
RcppExport SEXP _LDRegularization_cpp_projected_bootstrap_rank(SEXP X_targetSEXP, SEXP centerSEXP, SEXP n_bootSEXP, SEXP anchor_fractionSEXP, SEXP guard_fractionSEXP, SEXP target_fractionSEXP, SEXP basis_fractionSEXP, SEXP initial_rankSEXP, SEXP rank_blockSEXP, SEXP oversampleSEXP, SEXP bootstrap_extraSEXP, SEXP power_iterationsSEXP, SEXP n_threadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_target(X_targetSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< const double >::type anchor_fraction(anchor_fractionSEXP);
    Rcpp::traits::input_parameter< const double >::type guard_fraction(guard_fractionSEXP);
    Rcpp::traits::input_parameter< const double >::type target_fraction(target_fractionSEXP);
    Rcpp::traits::input_parameter< const double >::type basis_fraction(basis_fractionSEXP);
    Rcpp::traits::input_parameter< const int >::type initial_rank(initial_rankSEXP);
    Rcpp::traits::input_parameter< const int >::type rank_block(rank_blockSEXP);
    Rcpp::traits::input_parameter< const int >::type oversample(oversampleSEXP);
    Rcpp::traits::input_parameter< const int >::type bootstrap_extra(bootstrap_extraSEXP);
    Rcpp::traits::input_parameter< const int >::type power_iterations(power_iterationsSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_projected_bootstrap_rank(X_target, center, n_boot, anchor_fraction, guard_fraction, target_fraction, basis_fraction, initial_rank, rank_block, oversample, bootstrap_extra, power_iterations, n_threads, seed));
    return rcpp_result_gen;
END_RCPP
}
// cpp_source_moments
List cpp_source_moments(SEXP X_source, const bool center, const int block_size, const int n_threads, const bool compute_covariance);
RcppExport SEXP _LDRegularization_cpp_source_moments(SEXP X_sourceSEXP, SEXP centerSEXP, SEXP block_sizeSEXP, SEXP n_threadsSEXP, SEXP compute_covarianceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_source(X_sourceSEXP);
    Rcpp::traits::input_parameter< const bool >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type compute_covariance(compute_covarianceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_source_moments(X_source, center, block_size, n_threads, compute_covariance));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_LDRegularization_cpp_projected_bootstrap_rank", (DL_FUNC) &_LDRegularization_cpp_projected_bootstrap_rank, 14},
    {"_LDRegularization_cpp_source_moments", (DL_FUNC) &_LDRegularization_cpp_source_moments, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_LDRegularization(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
