# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_source_moments <- function(X_source, center, block_size, n_threads, compute_covariance) {
    .Call(`_LDRegularization_cpp_source_moments`, X_source, center, block_size, n_threads, compute_covariance)
}
